"""The persistent order store.

Same interface as the in-memory `OrderStore`, backed by Postgres, so routers and services never
learn which one they are talking to. This is what makes the board the same board on a field nurse's
phone and a case manager's laptop: both hit one API process, and that process reads rows every
device shares rather than a dict that dies with the container.

Two tables, mirroring the JSON fixtures one-to-one (see docs/DATA_MODEL.md). The columns are the
handful of fields the API queries or orders by; everything else on a row lives in a JSONB `data`
column, so adding a field to the fixtures needs no migration here.

Seeding is `ON CONFLICT DO NOTHING` against the same JSON the in-memory store reads: an empty
database fills itself on first boot, and a database with orders in it is left alone. A restart
therefore keeps what nurses placed instead of discarding it.

Synchronous on purpose. Every caller runs in FastAPI's threadpool and the store's interface is
sync, so a connection pool fits without turning every router and service async for no user-visible
gain.
"""

from __future__ import annotations

from typing import Any

from psycopg import Connection
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

from .fixtures import seed_order_events, seed_orders
from .store import BaseOrderStore, Row

# Columns promoted out of the JSONB blob because a query filters, sorts, or joins on them.
SCHEMA = """
CREATE TABLE IF NOT EXISTS orders (
    id            TEXT PRIMARY KEY,
    status        TEXT NOT NULL,
    -- True for an order placed through the app, false for one seeded from the fixtures. The demo
    -- driver only walks the former forward. Persisted rather than held in memory so an order keeps
    -- advancing after a restart, and advances while a second device watches.
    session_order BOOLEAN NOT NULL DEFAULT FALSE,
    data          JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS order_events (
    id       TEXT PRIMARY KEY,
    -- The SSE cursor. Clients reconnect with Last-Event-ID and ask for everything above it, so it
    -- has to be gapless and monotonic across processes — hence a sequence, not a Python counter.
    seq      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id TEXT NOT NULL,
    at       TEXT NOT NULL,
    data     JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS order_events_order_id_idx ON order_events (order_id);
CREATE INDEX IF NOT EXISTS order_events_seq_idx ON order_events (seq);
"""


class PostgresOrderStore(BaseOrderStore):
    """Orders and their timeline in Postgres. SSE fan-out is inherited unchanged."""

    def __init__(self, database_url: str) -> None:
        super().__init__()

        # Render's free tier allows few connections and runs one instance, so the pool stays small.
        self._pool = ConnectionPool(
            database_url, min_size=1, max_size=5, kwargs={"row_factory": dict_row}, open=True
        )
        self._migrate()
        self._seed()

    def _migrate(self) -> None:
        with self._pool.connection() as conn:
            conn.execute(SCHEMA)

    def _seed(self) -> None:
        """Fill an empty database from the JSON fixtures. A populated one is left untouched."""
        with self._pool.connection() as conn:
            for order in seed_orders():
                conn.execute(
                    "INSERT INTO orders (id, status, session_order, data) "
                    "VALUES (%s, %s, FALSE, %s) ON CONFLICT (id) DO NOTHING",
                    (order["id"], str(order.get("status", "")), Jsonb(order)),
                )

            # Seeded in timeline order so `seq` agrees with the order things actually happened in.
            for event in sorted(seed_order_events(), key=lambda row: row.get("at", "")):
                conn.execute(
                    "INSERT INTO order_events (id, order_id, at, data) "
                    "VALUES (%s, %s, %s, %s) ON CONFLICT (id) DO NOTHING",
                    (
                        event["id"],
                        str(event.get("orderId", "")),
                        str(event.get("at", "")),
                        Jsonb(event),
                    ),
                )

            # The fixtures carry their own ids, so the identity sequence never advanced during the
            # inserts above. Without this the first appended event collides on seq 1.
            conn.execute(
                "SELECT setval(pg_get_serial_sequence('order_events', 'seq'), "
                "COALESCE((SELECT MAX(seq) FROM order_events), 0) + 1, FALSE)"
            )

    # ── Orders ────────────────────────────────────────────────────────────────

    def list_orders(self) -> list[Row]:
        with self._pool.connection() as conn:
            rows = conn.execute("SELECT data FROM orders").fetchall()
        return [row["data"] for row in rows]

    def get_order(self, order_id: str) -> Row | None:
        """None for a missing id, never a raise — matches the rule in docs/DATA_MODEL.md."""
        with self._pool.connection() as conn:
            row = conn.execute(
                "SELECT data FROM orders WHERE id = %s", (order_id,)
            ).fetchone()
        return row["data"] if row else None

    def put_order(self, order: Row) -> None:
        with self._pool.connection() as conn:
            conn.execute(
                "INSERT INTO orders (id, status, data) VALUES (%s, %s, %s) "
                "ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status, data = EXCLUDED.data",
                (order["id"], str(order.get("status", "")), Jsonb(order)),
            )

    def next_order_id(self) -> str:
        """Continue the DME-##### series the fixtures use, and mark the id as session-placed.

        The insert claims the id in the same statement that derives it, so two concurrent creates
        cannot be handed the same one — the primary key rejects the loser and it retries.
        """
        while True:
            with self._pool.connection() as conn:
                row = conn.execute(
                    "SELECT COALESCE(MAX(SUBSTRING(id FROM 5)::BIGINT), 10000) AS high "
                    "FROM orders WHERE id ~ '^DME-[0-9]+$'"
                ).fetchone()
                order_id = f"DME-{int(row['high']) + 1}"

                # A placeholder row, replaced by put_order once the order is built. Reserving the
                # id here is what makes the derivation above safe under concurrency.
                claimed = conn.execute(
                    "INSERT INTO orders (id, status, session_order, data) "
                    "VALUES (%s, '', TRUE, '{}'::jsonb) ON CONFLICT (id) DO NOTHING RETURNING id",
                    (order_id,),
                ).fetchone()

            if claimed:
                return order_id

    def is_session_order(self, order_id: str) -> bool:
        """True for an order placed through the app, False for one seeded from the fixtures."""
        with self._pool.connection() as conn:
            row = conn.execute(
                "SELECT session_order FROM orders WHERE id = %s", (order_id,)
            ).fetchone()
        return bool(row["session_order"]) if row else False

    # ── Events ────────────────────────────────────────────────────────────────

    def events_for_order(self, order_id: str) -> list[Row]:
        with self._pool.connection() as conn:
            rows = conn.execute(
                "SELECT data, seq FROM order_events WHERE order_id = %s ORDER BY at",
                (order_id,),
            ).fetchall()
        return [{**row["data"], "seq": row["seq"]} for row in rows]

    def all_events(self) -> list[Row]:
        """Every event, oldest first. Feeds the frontend's boot snapshot in one request."""
        with self._pool.connection() as conn:
            rows = conn.execute("SELECT data, seq FROM order_events ORDER BY at").fetchall()
        return [{**row["data"], "seq": row["seq"]} for row in rows]

    def events_since(self, seq: int, limit: int = 100) -> list[Row]:
        """Backfill for a client that reconnects with a cursor."""
        with self._pool.connection() as conn:
            rows = conn.execute(
                "SELECT data, seq FROM order_events WHERE seq > %s ORDER BY seq LIMIT %s",
                (seq, limit),
            ).fetchall()
        return [{**row["data"], "seq": row["seq"]} for row in rows]

    def append_event(self, event: Row) -> Row:
        """Record an event and push it to every connected client."""
        with self._pool.connection() as conn:
            row = conn.execute(
                "INSERT INTO order_events (id, order_id, at, data) VALUES (%s, %s, %s, %s) "
                "RETURNING seq",
                (
                    event["id"],
                    str(event.get("orderId", "")),
                    str(event.get("at", "")),
                    Jsonb(event),
                ),
            ).fetchone()

        stored = {**event, "seq": row["seq"]}
        self._publish(stored)
        return dict(stored)

    def close(self) -> None:
        self._pool.close()


def connect(database_url: str) -> Connection[dict[str, Any]]:
    """A single connection, for scripts and tests that do not want a pool."""
    return Connection.connect(database_url, row_factory=dict_row)
